services:
  public-api:
    env_file: .env
    build:
      context: .
      dockerfile: public-api/Dockerfile
    ports:
      - '3001:3001'
    networks: [ microservices-net ]

  user-service:
    platform: linux/amd64
    env_file: .env
    build:
      context: .
      dockerfile: user-service/Dockerfile
    ports:
      - '3002:3002'
    environment:
      - USER_DB_FILE=/data/user-service/database.sqlite
    volumes:
      - ./data/user-service:/data/user-service
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:3002/health' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ microservices-net ]

  item-service:
    platform: linux/amd64
    env_file: .env
    build:
      context: .
      dockerfile: item-service/Dockerfile
    ports:
      - '3003:3003'
    environment:
      - ITEM_DB_FILE=/data/item-service/database.sqlite
    volumes:
      - ./data/item-service:/data/item-service
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:3003/health' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ microservices-net ]

  clash-data-service:
    platform: linux/amd64
    env_file: .env
    build:
      context: .
      dockerfile: clash-data-service/Dockerfile
    ports:
      - '3004:3004'
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:3004/health' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ microservices-net ]

  link-service:
    platform: linux/amd64
    env_file: .env
    build:
      context: .
      dockerfile: link-service/Dockerfile
    ports:
      - '3005:3005'
    environment:
      - LINK_DB_FILE=/data/link-service/database.sqlite
      - CLASH_DATA_SERVICE_URL=http://clash-data-service:3004
    volumes:
      - ./data/link-service:/data/link-service
    depends_on:
      - clash-data-service
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:3005/health' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ microservices-net ]

  meta-tracker-service:
    platform: linux/amd64
    env_file: .env
    build:
      context: .
      dockerfile: meta-tracker-service/Dockerfile
    ports:
      - '3006:3006'
    environment:
      - META_DB_FILE=/data/meta-tracker-service/database.sqlite
      - CLASH_DATA_SERVICE_URL=http://clash-data-service:3004
    volumes:
      - ./data/meta-tracker-service:/data/meta-tracker-service
    healthcheck:
      test: [ 'CMD', 'wget', '--spider', '-q', 'http://localhost:3006/health' ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: [ microservices-net ]

  api-gateway:
    env_file: .env
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - public-api
      - user-service
      - item-service
      - clash-data-service
      - link-service
      - meta-tracker-service
    networks: [ microservices-net ]
    environment:
      - USER_SERVICE_URL=http://user-service:3002
      - ITEM_SERVICE_URL=http://item-service:3003
      - CLASH_DATA_SERVICE_URL=http://clash-data-service:3004
      - LINK_SERVICE_URL=http://link-service:3005
      - META_TRACKER_SERVICE_URL=http://meta-tracker-service:3006
      - PUBLIC_API_URL=http://public-api:3001

  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - '8080:80'
    depends_on:
      - api-gateway
    networks: [ microservices-net ]

networks:
  microservices-net:
    driver: bridge
